apiVersion: batch/v1
kind: CronJob
metadata:
  name: joshlong-appearances-feed-cronjob
spec:
  # runs every hour on the hour
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: joshlong-appearances-feed-cronjob
            image: gcr.io/pgtm-jlong/joshlong-appearances-feed-cronjob
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: joshlong-appearances-feed-cronjob-secrets
          restartPolicy: OnFailure
