name: Josh's Appearances Feed Processor Kubernetes CronJob

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME  }}
  AUTHENTICATED_CREDENTIALS_JSON: ${{ secrets.AUTHENTICATED_CREDENTIALS_JSON }}
  CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
  OUTPUT_JSON: ${{ secrets.OUTPUT_JSON }}
  GIT_URI: ${{ secrets.GIT_URI }}
  SHEET_ID: ${{ secrets.SHEET_ID }}
  APP_NAME: joshlong-appearances-feed-cronjob
  GKE_CLUSTER:   ${{ secrets.GKE_CLUSTER }}
  GCLOUD_ZONE:  ${{ secrets.GCLOUD_ZONE }}
  NS_NAME:  ${{ secrets.NS_NAME }}
  GCLOUD_SA_KEY:  ${{ secrets.GCLOUD_SA_KEY }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: "Setup PATH"
        run: |
          P="${GITHUB_WORKSPACE}/bin"
          mkdir -p $P
          echo "${P}" >> $GITHUB_PATH

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER  }}'
          location: '${{ env.GCLOUD_ZONE }}'

      - run: |
          gcloud config set project $GCLOUD_PROJECT 
          gcloud --quiet auth configure-docker
          kubectl get pods

      - name: Build and Deploy the Appearances Processor to Kubernetes
        run: |
          kubectl get ns/$NS_NAME || kubectl create ns $NS_NAME 
          kubectl config set-context --current --namespace=$NS_NAME
          kubectl config view --minify | grep namespace: && echo "found the namespace.."

          cd $GITHUB_WORKSPACE
          mkdir -p $GITHUB_WORKSPACE/bin/
          (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.29.0/pack-v0.29.0-linux.tgz" | sudo tar -C  $GITHUB_WORKSPACE/bin/ --no-same-owner -xzv pack)
          ./deploy/deploy.sh

