name: Public Appearances Feed Processor

env:
  GH_PAT:  ${{ secrets.GH_PAT }}
  
  AUTHENTICATED_CREDENTIALS_JSON: ${{ secrets.AUTHENTICATED_CREDENTIALS_JSON }}
  CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}

  # GS_TAB_NAME	: ${{ secrets.GS_TAB_NAME	}}
  # GS_TAB_RANGE : ${{ secrets.GS_TAB_RANGE }}
  # GS_KEY : ${{ secrets.GS_KEY }}
  OUTPUT_JSON : ${{ secrets.OUTPUT_JSON }}
  GIT_USERNAME  : ${{ secrets.GIT_USERNAME  }}
  GIT_URI:  ${{ secrets.GIT_URI }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON  }}
  PICKLED_TOKEN: ${{ secrets.PICKLED_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '55 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Run the Google Sheet Ingest Routine 
        run: ./run.sh


