name: Appearances Feed Processor

env:
  GH_PAT:  ${{ secrets.GH_PAT }}
  GIT_USERNAME  : ${{ secrets.GIT_USERNAME  }}
  AUTHENTICATED_CREDENTIALS_JSON: ${{ secrets.AUTHENTICATED_CREDENTIALS_JSON }}
  CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
  OUTPUT_JSON : ${{ secrets.OUTPUT_JSON }}
  GIT_URI:  ${{ secrets.GIT_URI }}
  SHEET_ID: ${{ secrets.SHEET_ID }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '55 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Run the Google Sheet Ingest Routine
        run: ./run.sh

